[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.16" 
eth-rpc-url = "${RPC_URL}"
gas_reports = ["*"]
via_ir = true

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_KEY}" }
